version: "3"
services:
  rstudio:
    image: rocker/tidyverse:4.0.3
    environment:
      # Username：rstudio
      PASSWORD: "password"
    volumes:
      - ./work:/home/rstudio/work
    stdin_open: true
    tty: true
    ports:
      - 8787:8787
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - GRANT_SUDO=1
    tty: true
